name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: connect with DB
        uses: gtadam/mysql-deploy-action@v1
        with:
          DATABASE_HOST: 'mysql-rfam-public.ebi.ac.uk'
          DATABASE_PORT: '4497'
          DATABASE_NAME: 'Rfam'
          DATABASE_USERNAME: 'rfamro'
          DATABASE_PASSWORD: none
          DATABASE_SCRIPT: 'script.sql'
